name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
      - run: npm run build
      - run: git config --global user.email "dev@inkblottherapy.com"
      - run: git config --global user.name "Inkblot Engineering Team"
      - run: git add --all
      - run: git commit -m "new build"

      - uses: ad-m/github-push-action@master
        name: Push changes
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: "inkblot-therapy/github-version-bumper@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
